config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "games#index"

  post "/games/:id/genres", to: "games#add_genre", as: :add_genres
  post "/games/:id/platforms", to: "games#add_platform", as: :add_platforms
  post "/games/:id/developer", to: "games#add_developer"
  post "/games/:id/publisher", to: "games#add_publisher"

  delete "games/:id/publisher/:id", to: "games#remove_publisher", as: :remove_publisher
  delete "games/:id/developer/:id", to: "games#remove_developer", as: :remove_developer
  delete "games/:id/platform/:id", to: "games#remove_platform", as: :remove_platform
  delete "games/:id/genre/:id", to: "games#remove_genre", as: :remove_genre

  # Routes for devise
  devise_for :users, controllers: {
    omniauth_callbacks: "callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games
  resources :companies
  resources :users

  get "/:criticable/:criticable_id/critics", to: "critics#index", as: :critics
  post "/:criticable/:criticable_id/critics", to: "critics#create"
  patch "/:criticable/:criticable_id/critics/:critic_id", to: "critics#update"
  delete "/:criticable/:criticable_id/critics/:critic_id", to: "critics#destroy"
end

app/models/game.rb
class Game < ApplicationRecord
  # Enums
  enum category: { main_game: 0, expansion: 1 }

  # Associations
  has_one_attached :cover

  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies

  has_many :critics, as: :criticable, dependent: :destroy
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  belongs_to :parent, class_name: "Game", optional: true
  has_many :expansions, class_name: "Game",
                        foreign_key: "parent_id",
                        inverse_of: "parent",
                        dependent: :nullify
  has_one_attached :cover

  # Validations
  validates :name, uniqueness: true, presence: true
  validates :category, :cover, presence: true

  validates :rating, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100,
    allow_nil: true
  }
  validate :validate_parent

  def validate_parent
    if category == "main_game" && parent_id
      errors.add(:parent_id, "should be null")
    elsif category == "expansion" && Game.find_by(id: parent_id).nil?
      errors.add(:parent_id, "should be a valid game id")
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesConcern
  # get /games
  def index
    @games = Game.order(:name).page(params[:page]).per(5)
    authorize @games
  end

  # get /games/new
  def new
    @game = Game.new
    authorize @game

    @main_games = Game.main_game
  end

  # GET /games/:id
  def show
    @game = Game.find(params[:id])
    authorize @game

    @genres = @game.genres
    @platforms = @game.platforms

    @critics = policy_scope(@game.critics, policy_scope_class: CriticPolicy::Scope)

    show_pub_dev
  end

  def show_pub_dev
    @developers_total = InvolvedCompany.where(developer: true).map(&:company).uniq
    @developers = @game.involved_companies.where(developer: true).map(&:company)
    @developers_list = (@developers_total - @developers)

    @publishers_total = InvolvedCompany.where(publisher: true).map(&:company).uniq
    @publishers = @game.involved_companies.where(publisher: true).map(&:company)
    @publishers_list = (@publishers_total - @publishers)
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    authorize @game

    if @game.save
      redirect_to @game
    else
      render "new"
    end
  end

  # GET /games/:id/edit
  def edit
    @game = Game.find(params[:id])
    authorize @game

    @main_games = Game.main_game
  end

  # PATCH/PUT /games/:id
  def update
    @game = Game.find(params[:id])
    authorize @game

    if @game.update(game_params)
      redirect_to @game
    else
      render :edit
    end
  end

  # DELETE /games/:id
  def destroy
    @game = Game.find(params[:id])
    authorize @game

    @game.destroy
    redirect_to root_path
  end

  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id,
                                 :cover)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game, class: "form" do |form| %>
  <div class="input mb-16">
    <%= form.label :name, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.text_field :name, placeholder: "Game title", class: "input__content" %>
    </div>
    <% if game.errors.messages[:name].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:name].join(", ")%></span>
    <% end %>
  </div>
  
  <div class="input mb-16">
    <%= form.label :summary, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.text_area :summary, class: "input__content", placeholder: "About the game..." %>
    </div>
    <% if game.errors.messages[:summary].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:summary].join(", ")%></span>
    <% end %>
  <div>

  <div class="input mb-16">
    <%= form.label :release_date, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.date_field :release_date, class: "input__content", placeholder: "dd/mm/yyyy" %>
    </div>
    <% if game.errors.messages[:release_date].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:release_date].join(", ")%></span>
    <% end %>
  </div>
  
  <div class="input mb-16">
    <%= form.label :rating, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.number_field :rating, in: 0.0..100.0, step: 0.1, class: "input__content", placeholder: "0.0" %>
    </div>
    <% if game.errors.messages[:rating].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:rating].join(", ")%></span>
    <% end %>
  </div>

  <div class="select mb-16">
    <%= form.label :category, class: "content--xs overline" %>
    <%= form.select :category, options_for_select([["Main game", "main_game"], ["Expansion", "expansion"]]), class: "select__input" %>
    <% if game.errors.messages[:category].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:category].join(", ")%></span>
    <% end %>
  </div>

  <div class="select mb-16">
    <%= form.label :parent_id, class: "content--xs overline" %>
    <%= form.collection_select :parent_id, @main_games, :id, :name, prompt: "No Parent", class: "select__input" %>
    <% if game.errors.messages[:parent_id].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:parent_id].join(", ")%></span>
    <% end %>
  </div>
  
  <div class="input mb-16">
    <%= form.label :cover, class: "content--xs overline" %>
    <%= image_tag game.cover, class: "form__img" if game.cover.attached? %>
    <%= form.file_field :cover, class: "input__content" %>
    <% if game.errors.messages[:cover].any? %>
      <span class="content--sm input__error-message"><%= game.errors.messages[:cover].join(", ")%></span>
    <% end %>
  </div>

  <%= form.submit class: "btn btn--primary mb-16" %>
<% end %>

<div class="text-center">
  <%= link_to "Back", :back, class: "anchor" %>
</div>

app/views/games/_game-detail.html.erb
<p class="content--xs text-center"><%= game.summary %></p>

<div>
  <p class="content--sm">Genres:</p>
  <div class="btn--relations__container">
    <% genres.each do |genre| %>
      <div class="btn--relations">
        <%= genre.name %>
        <%= link_to image_tag('/icons/cross.png'), remove_genre_path(game, genre_id: genre), method: :delete, class: "btn--relations__icon" if policy(genre).destroy? %>
      </div>
    <% end %>
  </div>
</div>

<div>
  <p class="content--sm">Platforms:</p>
  <div class="btn--relations__container">
    <% platforms.each do |platform| %>
      <div class="btn--relations">
        <%= platform.name %>
        <%= link_to image_tag('/icons/cross.png'), remove_platform_path(game, platform_id: platform), method: :delete, class: "btn--relations__icon" if policy(platform).destroy? %>
      </div>
    <% end %>
  </div>
</div>

<div>
  <p class="content--sm">Developer:</p>
  <div class="btn--relations__container">
    <% developers.each do |developer| %>
      <div class="btn--relations">
        <%= developer.name %>
        <%= link_to image_tag('/icons/cross.png'), remove_developer_path(game, developer_id: developer), method: :delete, class: "btn--relations__icon" if policy(developer).destroy? %>
      </div>
    <% end %>
  </div>
</div>

<div>
  <p class="content--sm">Publisher:</p>
  <div class="btn--relations__container">
    <% publishers.each do |publisher| %>
      <div class="btn--relations">
        <%= publisher.name %>
        <%= link_to image_tag('/icons/cross.png'), remove_publisher_path(game, publisher_id: publisher), method: :delete, class: "btn--relations__icon" if policy(publisher).destroy? %>
      </div>
    <% end %>
  </div>
</div>

<% if policy(game).edit? %>
  <h3 class="heading--xs">Add Relations</h3>

  <%= form_with url: add_genres_path(game), class: "flex gap-8" do |form| %>
    <%= form.collection_select :id_genre, (Genre.all - game.genres), :id, :name, { prompt: "Select genre" }, { class: "select--relations" } %>
    <%= form.submit "Add Genre", class: "btn btn--primary btn--small" %>
  <% end %>

  <%= form_with url: add_platforms_path(game), class: "flex gap-8" do |form| %>
    <%= form.collection_select :id_platform, (Platform.all - game.platforms), :id, :name, { prompt: "Select platform" }, { class: "select--relations" } %>
    <%= form.submit "Add Platform", class: "btn btn--primary btn--small" %>
  <% end %>

  <%= form_with url: "/games/#{game.id}/developer", class: "flex gap-8" do |form| %>
    <%= form.collection_select :develop_id, @developers_list, :id, :name, { prompt: "Select developer" }, { class: "select--relations" } %>
    <%= form.submit "Add Developer", class: "btn btn--primary btn--small" %>
  <% end %>

  <%= form_with url: "/games/#{game.id}/publisher", class: "flex gap-8" do |form| %>
    <%= form.collection_select :publisher_id, @publishers_list, :id, :name, { prompt: "Select publisher" }, { class: "select--relations" } %>
    <%= form.submit "Add Publisher", class: "btn btn--primary btn--small" %>
  <% end %>
<% end %>

app/views/games/edit.html.erb
<h2>Edit game</h2>

<%= render 'form', game: @game, main_games: @main_games %>

app/views/games/index.html.erb
<h2 class="heading--sm">Games</h2>

<%= link_to "New Game", new_game_path, class:"btn btn--primary btn--small" if policy(@games.first).create? %>

<% @games.each do |game| %>
  <div class="card">
    <%= link_to game do %>
      <div class="card__img">
        <%= image_tag game.cover, class: "card__img--cover" %>
      </div>
    <% end %>

    <div class="card__details">
      <%= link_to game do %>
        <div class="flex space-between">
          <div>
            <p class="content--lg"><%= game.name %></p>
            <% if game.release_date %>
              <p class="content--xs"><%= game.release_date.year %></p>
            <% end %>
          </div>

          <% if game.rating %>
            <p class="rating-btn"><%= game.rating %></p>
          <% end %>
        </div>
      <% end %>

      <%= link_to game do %>
        <p class="card__body content--xs">
          <%= game.summary %>
        </p>
      <% end %>

      <div class="flex space-between">
        <%= link_to game do %>
          <p class="content--xs">
            <%= pluralize(game.critics.size, "critic") %>
          </p>
        <% end %>

        <div class="flex gap-8">
          <%= link_to image_tag('/icons/edit.png'), edit_game_path(game), class: "content--xs" if policy(game).edit? %>
          <%= link_to image_tag('/icons/delete.png'), game_path(game), method: :delete, data: { confirm: "Are you sure?" }, class: "content--xs" if policy(game).destroy? %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center content--xs">
  <%= paginate @games %>
  <%= page_entries_info @games, entry_name: 'game' %>
</div>

app/views/games/new.html.erb
<h2>New Game</h2>

<%= render 'form', game: @game, main_games: @main_games %>

app/views/games/show.html.erb
<%= render "shared/games-header", model: @game %>

<ul class="details_navbar mb-16">
  <li class="details_navbar__item details_navbar--selected"><%= link_to 'Game Details', game_path(@game) %></li>
  <li class="details_navbar__item"><%= link_to "Critics (#{@critics.size})", critics_path(criticable: "games", criticable_id: @game.id) %></li>
</ul>

<%= render("game-detail",
  game: @game,
  genres: @genres,
  platforms: @platforms,
  developers: @developers,
  publishers: @publishers
) %>

<div class="text-center">
  <%= link_to "Back", :back, class: "anchor" %>
</div>