config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "games#index"

  post "/games/:id/genres", to: "games#add_genre", as: :add_genres
  post "/games/:id/platforms", to: "games#add_platform", as: :add_platforms
  post "/games/:id/developer", to: "games#add_developer"
  post "/games/:id/publisher", to: "games#add_publisher"

  delete "games/:id/publisher/:id", to: "games#remove_publisher", as: :remove_publisher
  delete "games/:id/developer/:id", to: "games#remove_developer", as: :remove_developer
  delete "games/:id/platform/:id", to: "games#remove_platform", as: :remove_platform
  delete "games/:id/genre/:id", to: "games#remove_genre", as: :remove_genre

  # Routes for devise
  devise_for :users, controllers: {
    omniauth_callbacks: "callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games
  resources :companies
  resources :users

  get "/:criticable/:criticable_id/critics", to: "critics#index", as: :critics
  post "/:criticable/:criticable_id/critics", to: "critics#create"
  patch "/:criticable/:criticable_id/critics/:critic_id", to: "critics#update"
  delete "/:criticable/:criticable_id/critics/:critic_id", to: "critics#destroy"
end

app/models/company.rb
class Company < ApplicationRecord
  # Associations
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies

  has_many :critics, as: :criticable, dependent: :destroy
  has_one_attached :cover

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :cover, presence: { message: "can't be blank" }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  def index
    @companies = Company.order(:name).page(params[:page]).per(5)
    authorize @companies
  end

  # GET /companies/:id
  def show
    @company = Company.find(params[:id])
    authorize @company

    @critics = policy_scope(@company.critics, policy_scope_class: CriticPolicy::Scope)

    render :show
  end

  # GET /companies/new
  def new
    @company = Company.new
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    authorize @company

    return redirect_to @company if @company.save

    render :new
  end

  # GET /companies/:id/edit
  def edit
    @company = Company.find(params[:id])
    authorize @company
  end

  # PATCH /companies/:id
  def update
    @company = Company.find(params[:id])
    authorize @company

    return redirect_to @company if @company.update(company_params)

    render :edit
  end

  # DELETE /companies/:id
  def destroy
    @company = Company.find(params[:id])
    authorize @company

    @company.destroy
    redirect_to companies_path
  end

  private

  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country, :cover)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company-detail.html.erb
<p class="content--xs text-center"><%= company.description %></p>

<h3 class="heading--xs">Games (<%= @company.games_count %>)</h3>

<% @company.games.each do |game| %>
  <div class="card">
    <%= link_to game do %>
      <div class="card__img">
        <%= image_tag game.cover, class: "card__img--cover" %>
      </div>
    <% end %>

    <div class="card__details">
      <%= link_to game do %>
        <div class="flex space-between">
          <div>
            <p class="content--lg"><%= game.name %></p>
            <% if game.release_date %>
              <p class="content--xs"><%= game.release_date.year %></p>
            <% end %>
          </div>

          <% if game.rating %>
            <p class="rating-btn"><%= game.rating %></p>
          <% end %>
        </div>
      <% end %>

      <%= link_to game do %>
        <p class="card__body content--xs">
          <%= game.summary %>
        </p>
      <% end %>

      <div class="flex space-between">
        <%= link_to game do %>
          <p class="content--xs">
            <%= pluralize(game.critics.size, "critic") %>
          </p>
        <% end %>

        <div class="flex gap-8">
          <%= link_to image_tag('/icons/edit.png'), edit_game_path(game), class: "content--xs" if policy(game).edit? %>
          <%= link_to image_tag('/icons/delete.png'), game_path(game), method: :delete, data: { confirm: "Are you sure?" }, class: "content--xs" if policy(game).destroy? %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= form_with model: company, class: "form" do |form| %>
  <div class="input mb-16">
    <%= form.label :name, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.text_field :name, placeholder: "Company SA", class: "input__content" %>
    </div>
    <% if company.errors.messages[:name].any? %>
      <span class="content--sm input__error-message"><%= company.errors.messages[:name].join(", ")%></span>
    <% end %>
  </div>

  <div class="input mb-16">
    <%= form.label :description, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.text_area :description, placeholder: "About the company...", class: "input__content" %>
    </div>
    <% if company.errors.messages[:description].any? %>
      <span class="content--sm input__error-message"><%= company.errors.messages[:description].join(", ")%></span>
    <% end %>
  </div>

  <div class="input mb-16">
    <%= form.label :start_date, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.date_field :start_date, placeholder: "dd/mm/yyyy", class: "input__content" %>
    </div>
    <% if company.errors.messages[:start_date].any? %>
      <span class="content--sm input__error-message"><%= company.errors.messages[:start_date].join(", ")%></span>
    <% end %>
  </div>

  <div class="input mb-16">
    <%= form.label :country, class: "content--xs overline" %>
    <div class="input__container">
      <%= form.text_field :country, placeholder: "Somewhere", class: "input__content" %>
    </div>
    <% if company.errors.messages[:country].any? %>
      <span class="content--sm input__error-message"><%= company.errors.messages[:country].join(", ")%></span>
    <% end %>
  </div>

  <div class="input mb-16">
    <%= form.label :cover, class: "content--xs overline" %>
    <%= image_tag company.cover, class: "form__img" if company.cover.attached? %>
    <%= form.file_field :cover, class: "input__content" %>
    <% if company.errors.messages[:cover].any? %>
      <span class="content--sm input__error-message"><%= company.errors.messages[:cover].join(", ")%></span>
    <% end %>
  </div>

  <%= form.submit class: "btn btn--primary" %>
<% end %>

<div class="text-center">
  <%= link_to "Back", :back, class: "anchor" %>
</div>

app/views/companies/edit.html.erb
<h2>Edit Company</h2>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<h2 class="heading--sm">Companies</h2>

<%= link_to 'New Company', new_company_path, class:"btn btn--primary btn--small" if policy(@companies.first).create? %>

<% @companies.each do |company| %>
  <div class="card">
    <%= link_to company do %>
      <div class="card__img">
        <%= image_tag company.cover, class: "card__img--cover" %>
      </div>
    <% end %>

    <div class="card__details">
      <%= link_to company do %>
        <div>
          <p class="content--lg"><%= company.name %></p>
          <p class="content--xs">
            <%= company.start_date.year if company.start_date %> 
            - 
            <%= company.country %>
          </p>
        </div>
      <% end %>

      <%= link_to company do %>
        <p class="card__body content--xs">
          <%= company.description %>
        </p>
      <% end %>

      <div class="flex space-between">
        <%= link_to company do %>
          <p class="content--xs">
            <%= pluralize(company.critics.size, "critic") %>
          </p>
        <% end %>

        <div class="flex gap-8">
          <%= link_to image_tag('/icons/edit.png'), edit_company_path(company), class: "content--xs" if policy(company).edit? %>
          <%= link_to image_tag('/icons/delete.png'), company_path(company), method: :delete, data: { confirm: "Are you sure?" }, class: "content--xs" if policy(company).destroy? %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center content--xs">
  <%= paginate @companies %>
  <%= page_entries_info @companies, entry_name: 'company' %>
</div>

app/views/companies/new.html.erb
<h2>New Company</h2>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<%= render "shared/companies-header", model: @company %>

<ul class="details_navbar mb-16">
  <li class="details_navbar__item details_navbar--selected"><%= link_to 'Company Details', company_path(@company) %></li>
  <li class="details_navbar__item"><%= link_to "Critics (#{@critics.size})", critics_path(criticable: "companies", criticable_id: @company.id) %></li>
</ul>

<%= render "company-detail", company: @company %>

<div class="text-center">
  <%= link_to "Back", :back, class: "anchor" %>
</div>