config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "games#index"

  post "/games/:id/genres", to: "games#add_genre", as: :add_genres
  post "/games/:id/platforms", to: "games#add_platform", as: :add_platforms
  post "/games/:id/developer", to: "games#add_developer"
  post "/games/:id/publisher", to: "games#add_publisher"

  delete "games/:id/publisher/:id", to: "games#remove_publisher", as: :remove_publisher
  delete "games/:id/developer/:id", to: "games#remove_developer", as: :remove_developer
  delete "games/:id/platform/:id", to: "games#remove_platform", as: :remove_platform
  delete "games/:id/genre/:id", to: "games#remove_genre", as: :remove_genre

  # Routes for devise
  devise_for :users, controllers: {
    omniauth_callbacks: "callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games
  resources :companies
  resources :users

  get "/:criticable/:criticable_id/critics", to: "critics#index", as: :critics
  post "/:criticable/:criticable_id/critics", to: "critics#create"
  patch "/:criticable/:criticable_id/critics/:critic_id", to: "critics#update"
  delete "/:criticable/:criticable_id/critics/:critic_id", to: "critics#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  # Associations
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies

  has_many :critics, as: :criticable, dependent: :destroy
  has_one_attached :cover

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :cover, presence: { message: "can't be blank" }
end

app/models/critic.rb
class Critic < ApplicationRecord
  # Associations
  belongs_to :user, counter_cache: true
  belongs_to :criticable, polymorphic: true

  # Validations
  validates :title, presence: true, length: { maximum: 40 }
  validates :body, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  # Enums
  enum category: { main_game: 0, expansion: 1 }

  # Associations
  has_one_attached :cover

  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies

  has_many :critics, as: :criticable, dependent: :destroy
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  belongs_to :parent, class_name: "Game", optional: true
  has_many :expansions, class_name: "Game",
                        foreign_key: "parent_id",
                        inverse_of: "parent",
                        dependent: :nullify
  has_one_attached :cover

  # Validations
  validates :name, uniqueness: true, presence: true
  validates :category, :cover, presence: true

  validates :rating, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100,
    allow_nil: true
  }
  validate :validate_parent

  def validate_parent
    if category == "main_game" && parent_id
      errors.add(:parent_id, "should be null")
    elsif category == "expansion" && Game.find_by(id: parent_id).nil?
      errors.add(:parent_id, "should be a valid game id")
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  # Associations
  has_and_belongs_to_many :games

  # Validations
  validates :name, presence: true, uniqueness: true
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  # Associations
  belongs_to :company, counter_cache: "games_count"
  belongs_to :game

  # Validations
  validates :company,
            uniqueness: { scope: :game, message: "and Game combination already taken" }
  validates :developer, :publisher, inclusion: { in: [true, false] }
end

app/models/platform.rb
class Platform < ApplicationRecord
  # Enums
  enum category: {
    console: 0,
    arcade: 1,
    platform: 2,
    operating_system: 3,
    portable_console: 4,
    computer: 5
  }

  # Associations
  has_and_belongs_to_many :games

  # Validations
  validates :name, uniqueness: true, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Enums
  enum role: { contributor: 0, admin: 1 }

  # Associations
  has_many :critics, dependent: :destroy
  has_many :authentications, dependent: :destroy

  # Validations

  validates :email, uniqueness: true, presence: true
  validates :username, uniqueness: true, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github gitlab]

  # To be used with omniauth
  def self.from_omniauth(auth)
    authentication = Authentication.where(
      provider: auth.provider,
      uid: auth.uid
    ).first_or_initialize

    unless authentication.user
      user = find_by(email: auth.info.email)
      user ||= User.create(extract_user_data(auth))

      authentication.user = user
      authentication.save
    end

    authentication.user
  end

  def self.extract_user_data(auth)
    info = auth.info
    token = Devise.friendly_token[6, 14]
    username = info.nickname || info.name.downcase.gsub(" ", "_")
    {
      username: username,
      email: info.email,
      default_password: token,
      password: token
    }
  end

  private_class_method :extract_user_data
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesConcern
  # get /games
  def index
    @games = Game.order(:name).page(params[:page]).per(5)
    authorize @games
  end

  # get /games/new
  def new
    @game = Game.new
    authorize @game

    @main_games = Game.main_game
  end

  # GET /games/:id
  def show
    @game = Game.find(params[:id])
    authorize @game

    @genres = @game.genres
    @platforms = @game.platforms

    @critics = policy_scope(@game.critics, policy_scope_class: CriticPolicy::Scope)

    show_pub_dev
  end

  def show_pub_dev
    @developers_total = InvolvedCompany.where(developer: true).map(&:company).uniq
    @developers = @game.involved_companies.where(developer: true).map(&:company)
    @developers_list = (@developers_total - @developers)

    @publishers_total = InvolvedCompany.where(publisher: true).map(&:company).uniq
    @publishers = @game.involved_companies.where(publisher: true).map(&:company)
    @publishers_list = (@publishers_total - @publishers)
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    authorize @game

    if @game.save
      redirect_to @game
    else
      render "new"
    end
  end

  # GET /games/:id/edit
  def edit
    @game = Game.find(params[:id])
    authorize @game

    @main_games = Game.main_game
  end

  # PATCH/PUT /games/:id
  def update
    @game = Game.find(params[:id])
    authorize @game

    if @game.update(game_params)
      redirect_to @game
    else
      render :edit
    end
  end

  # DELETE /games/:id
  def destroy
    @game = Game.find(params[:id])
    authorize @game

    @game.destroy
    redirect_to root_path
  end

  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id,
                                 :cover)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/critics_helper.rb
module CriticsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C4CriticsRc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'style.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container m-auto">
      <header class="navbar align-center">
        <%= link_to image_tag("critic-logo.png"), root_path, class: "navbar__logo" %>

        <input type="checkbox" id="open" class="menu-checkbox">
        <label for="open" class="menu-open"></label>

        <% if user_signed_in? %>
          <nav class="menu absolute">
            <div class="container">
              <ul class="menu--content content--sm">
                <li>Welcome <%= current_user.username %>!</li>
                <li class="primary-500"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li class="primary-500"><%= link_to 'Games', games_path %></li>
                <li class="primary-500"><%= link_to 'Companies', companies_path %></li>
                <li class="btn btn--secondary btn--small"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </div>
          </nav>
        <% else %>
          <nav class="menu absolute">
            <div class="container">
              <ul class="menu--content content--sm">
                <li>Sign in to start criticizing games and companies</li>
                <li class="btn btn--primary btn--small"> <%= link_to 'Sign in', new_user_session_path %> </li>
              </ul>
            </div>
          </nav>
        <% end %>
      </header>

      <div class="absolute">
        <% flash.each do |type, message|%>
          <div class="flex gap-16 flash-card flash-card--fade_away">
            <%= image_tag "/images/icons/#{type}.svg" %>
            <div class="text-left">
              <p class="heading heading--xs"><%=type.to_s.capitalize%></p>
              <p class="content--lg"><%=message%></p>
            </div>
          </div>
        <% end %>
      </div>

      <%= yield %>

      <footer>
        <p class="footer--txt content--sm">© 2021 - Codeable Critics</p>
        <p class="content--sm">Build with <span class="footer--heart">♥</span> by</p>

        <div class="footer--social-container content--xs">
          <div class="footer--social-name">
            <%= image_tag "linkdin-vector.svg" %>
            <p> Ana Isabel León</p>
          </div>
          <div class="footer--social-name">
            <%= image_tag "linkdin-vector.svg" %>
            <p> Andrés Scribani</p>
          </div>
          <div class="footer--social-name">
            <%= image_tag "linkdin-vector.svg"%>
            <p> Ever Ponce</p>
          </div>
          <div class="footer--social-name">
            <%= image_tag "linkdin-vector.svg" %>
            <p> Mindy León</p>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/shared/_companies-header.html.erb
<div class="details__img">
  <%= image_tag model.cover, class: "details__img--cover" if model.cover.attached? %>
</div>

<div class="flex space-between">
  <div>
    <p class="heading--sm"><%= model.name %></p>
    <p class="content--xs">
      <%= model.start_date.year if model.start_date %> 
      - 
      <%= model.country %>
    </p>
  </div>
</div>

app/views/shared/_criticable_form.html.erb
<%= form_with(url: "/#{criticable_type}/#{criticable_id}/critics", class: "form") do |form| %>
  <div class="input mb-16">
    <%= form.label :title, class:"content--xs overline"%>
    <div class="input__container">
      <%= form.text_field :title, class: "input__content", placeholder: "Critic title", required: true %>
    </div>
  </div>

  <div class="input mb-16">
    <%= form.label :body, class:"content--xs overline"%>
    <div class="input__container">
      <%= form.text_area :body, class: "input__content", placeholder: "Critic body...", required: true %>
    </div>
  </div>

  <%= form.submit "Create Critic", class: "btn btn--primary" %>
<% end %>

<% critics.each do |critic| %>
  <div class="critic__details">
    <div class="shadow"></div>

    <div>
      <p class="bold"><%= critic.title %></p>
      <p class="content--xs">by <%= critic.user.username %></p>
    </div>

    <p><%= critic.body %></p>

    <div class="flex space-between align-center">
      <p class="content--sm gray-300">Send <%= time_ago_in_words(critic.created_at) %> ago</p>

      <div class="flex gap-8 align-center">
        <% unless critic.approved %>
          <% if policy(critic).edit? %>
            <%= link_to(
              "Approve",
              "/#{criticable_type}/#{criticable_id}/critics/#{critic.id}",
              method: :patch,
              class: "content--sm primary-500"
            ) %>
          <% else %>
            <p class="content--sm gray-300">Pending approval</p>
          <% end %>
        <% end %>

        <%= link_to(
          image_tag("trash.svg", :alt => "delete"),
          "/#{criticable_type}/#{criticable_id}/critics/#{critic.id}",
          method: :delete,
          data: { confirm: "Do you want to delete it?" },
          class: "content--xs"
        ) if policy(critic).edit? %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_games-header.html.erb
<div class="details__img">
  <%= image_tag model.cover, class: "details__img--cover" if model.cover.attached? %>
</div>

<div class="flex space-between">
  <div>
    <p class="heading--sm"><%= model.name %></p>
    <p class="content--xs"><%= model.release_date.year if model.release_date %></p>
  </div>

  <% if model.rating %>
    <p class="rating-btn"><%= model.rating %></p>
  <% end %>
</div>